= BROWSER-DEFRAG
:toc:
:toc-placement!:
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

*browser-defrag* is a tool for defragging browser's database files.
It will help to reduce the storage size of browser's profile.

toc::[]

== Installation

=== Cargo

*browser-defrag* can be used without installation by run:

[source,console]
$ cargo run

To install in `$HOME/.cargo/bin`, run:
[source,console]
$ cargo install --path .

=== Arch Linux
To build and install arch package from GIT source:

[source,console]
$ git clone https://github.com/bpetlert/browser-defrag.git
$ cd browser-defrag
$ makepkg -p PKGBUILD.local
$ pacman -U browser-defrag-xxxx-1-x86_64.pkg.tar

== Supported Browsers

=== Linux

* [x] Firefox
** [x] Single Profile
** [x] Multiple Profiles

* [x] Firefox Developer Edition
** [x] Single Profile
** [x] Multiple Profiles

* [x] Chromium

* [x] Unknown Browser: use a given profile's path

== Usage

To start defragging database files for a browser, use `browser-defrag <BROWSER-NAME>`.
The name of supported browser can be found using `browser-defrag -h`.

The maximum searching of descendent directory is default to 2.
This can be changed by using `--max-depth <DEPTH>`

To show the list of database files without defragging, uses `--dry-run`.

.Defrag Firefox's database
[source,console]
$ browser-defrag firefox

.Defrag unknown browser with a given profile path
[source,console]
$ browser-defrag unknown --profile-path=$HOME/.config/chromium

== License

*link:./COPYING[GNU General Public License v3.0 or later]*
